

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import sql_nube.ConexionNube;
import sql_nube.Integrantes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yazmi
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtID = new javax.swing.JTextPane();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLinea = new javax.swing.JTextPane();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNArt = new javax.swing.JTextPane();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNReal = new javax.swing.JTextPane();
        jTextField5 = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        txtColorF = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblIntegrantes = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 10));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("id");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 36, 71, -1));

        jScrollPane1.setViewportView(txtID);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 76, 79, -1));

        jTextField2.setText("Linea");
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 71, -1));

        jScrollPane2.setViewportView(txtLinea);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 142, -1));

        jTextField3.setText("Nombre Artistico");
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 120, -1));

        jScrollPane3.setViewportView(txtNArt);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 129, -1));

        jTextField4.setText("Nombre Real");
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 110, -1));

        jScrollPane4.setViewportView(txtNReal);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 116, -1));

        jTextField5.setText("Color Favorito");
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 100, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));
        jPanel2.add(txtColorF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 133, -1));

        tblIntegrantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idIntegrantes", "nombreArtistico", "nombreReal", "linea", "colorFavorito"
            }
        ));
        tblIntegrantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIntegrantesMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblIntegrantes);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 560, 100));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tblIntegrantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIntegrantesMouseClicked
       
        try {
             int fila= tblIntegrantes.getSelectedRow();
        int  idIntegrantes= Integer.parseInt( tblIntegrantes.getValueAt(fila, 0).toString());
         ConexionNube connMySQL = new ConexionNube();
        Connection conn = connMySQL.open();
        ResultSet rs;
        PreparedStatement pstmt;
            pstmt= conn.prepareStatement("SELECT idIntegrante,nombreArtistico,nombreReal,linea,colorFavorito FROM  integrantes where idIntegrante=?");
           pstmt.setInt(1, idIntegrantes);
           rs= pstmt.executeQuery();
            while (rs.next()) {  
                System.out.println(idIntegrantes);
                txtID.setText("idIntegrante");
                txtNArt.setText(rs.getString("nombreArtistico"));
                 txtNReal.setText(rs.getString("nombreReal"));
                  txtLinea.setText(rs.getString("linea"));
                   txtColorF.setText(rs.getString("colorFavorito"));
            }
           
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_tblIntegrantesMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            guardar();
            limpiar();
            cargarTabla();
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.toString());
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            // TODO add your handling code here:
            actualizar();
             limpiar();
            cargarTabla();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
        limpiar();
        cargarTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblIntegrantes;
    private javax.swing.JTextPane txtColorF;
    private javax.swing.JTextPane txtID;
    private javax.swing.JTextPane txtLinea;
    private javax.swing.JTextPane txtNArt;
    private javax.swing.JTextPane txtNReal;
    // End of variables declaration//GEN-END:variables
public void guardar() throws SQLException{
    ConexionNube connMySQL = new ConexionNube();
        Connection conn = connMySQL.open();
        Statement stmnt = null;
        ResultSet rs = null;
        try {
            
        stmnt = conn.createStatement();
         
         String query1 = "insert into integrantes (nombreArtistico,nombreReal,linea,colorFavorito) "
                    + "VALUES ("+'"'+txtNArt.getText()+'"'
                    + ','+'"' + txtNReal.getText()+'"'
                    + ','+'"' + txtLinea.getText()+'"'
                    + ','+'"' + txtColorF.getText()+'"'+  ");";
            stmnt.execute(query1);
              String query2 = "SELECT LAST_INSERT_ID()";
            rs = stmnt.executeQuery(query2);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.toString());
        }
            // Se obtiene el id de la venta que se ha insertado
          
            stmnt.close();
           connMySQL.close();
        JOptionPane.showMessageDialog(null, "Se guardo Correctamente");
        
}

public void cargarTabla(){
    DefaultTableModel modelTabla = (DefaultTableModel) tblIntegrantes.getModel();
    modelTabla.setRowCount(0);
    PreparedStatement pstmt;
    ResultSet rs;
   ResultSetMetaData rsmd;
   int columnas;
    
        try {
            ConexionNube connMySQL = new ConexionNube();
        Connection conn = connMySQL.open();
            pstmt= conn.prepareStatement("select * from integrantes;");
            rs= pstmt.executeQuery();
            rsmd= (ResultSetMetaData) rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
             while (rs.next()) {  
               Object[] fila= new Object[columnas];
               for(int indice=0;indice< columnas; indice++){
               fila[indice]= rs.getObject(indice+1);
               
                       }
               modelTabla.addRow(fila);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        

}
public void limpiar(){
   txtColorF.setText("");
   txtID.setText("");
   txtLinea.setText("");
   txtNArt.setText("");
   txtNReal.setText("");

}
public void actualizar() throws SQLException{
    ConexionNube connMySQL = new ConexionNube();
        Connection conn = connMySQL.open();
        Statement stmnt = null;
        
        try {
            
        stmnt = conn.createStatement();
         int id=1;
 
         String query1 = "update integrantes SET"
                    + "nombreArtistico="+'"'+txtNArt.getText()+'"'
                    + "nombreReal="+
                    + ','+'"' + txtNReal.getText()+'"'
                     + "linea="+
                    + ','+'"' + txtLinea.getText()+'"'
                  + "colorFavorito="+
                    + ','+'"' + txtColorF.getText()+'"'+  "WHERE idIntegrante="+id+";";
            stmnt.execute(query1);
              
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.toString());
        }
            // Se obtiene el id de la venta que se ha insertado
          
            stmnt.close();
           connMySQL.close();
        JOptionPane.showMessageDialog(null, "Se guardo Correctamente");
        
}
public void eliminar(){
   int fila = tblIntegrantes.getSelectedRow();
int idIntegrante = Integer.parseInt(tblIntegrantes.getValueAt(fila,0).toString());
 try{
 PreparedStatement pstmt;
 ResultSet rs;
 ConexionNube conNube = new ConexionNube();
Connection conn;
       conn = conNube.open();
 pstmt = conn.prepareStatement("DELETE FROM integrantes WHERE idIntegrante = ?;");
 pstmt.setInt(1, idIntegrante);
pstmt.executeUpdate();
 JOptionPane.showMessageDialog(null,"Eliminacion Exitosa :)");
limpiar();
cargarTabla();
}catch(Exception ex){
JOptionPane.showMessageDialog(null,ex.toString());
}
}


}
